language: node_js
matrix:
  include:
    - node_js: "0.11"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "0.12"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "iojs-v1.5"
    - node_js: "iojs"
  fast_finish: true
script: 
  - npm test